import { expect, type Page, test } from "@playwright/test";

/** Letters only: the backend never sends terms with digits to the AI. */
function randomWord(prefix: string): string {
  const letters = "abcdefghijklmnopqrstuvwxyz";
  return prefix + Array.from({ length: 6 }, () => letters[Math.floor(Math.random() * letters.length)]).join("");
}

const searchBox = (page: Page) => page.getByRole("combobox", { name: "So‘z yoki ibora kiriting" });

async function search(page: Page, q: string) {
  await page.goto("/");
  const box = searchBox(page);
  await box.fill(q);
  await box.press("Enter");
}

test("exact search redirects to the word page with translations", async ({ page }) => {
  await search(page, "run");
  await expect(page).toHaveURL(/\/w\/en\/run$/);
  await expect(page.getByTestId("headword")).toHaveText("run");
  await expect(page.getByTestId("primary-translations")).toContainText("yugurmoq");
  await expect(page.getByTestId("sense").first()).toContainText("oyoqda tez harakatlanmoq");
});

test("typo shows 'did you mean'", async ({ page }) => {
  await search(page, "beutiful");
  const hint = page.getByTestId("did-you-mean");
  await expect(hint).toContainText("beautiful");
  await expect(hint).toContainText("nazarda tutdingizmi");
  await hint.getByRole("link", { name: /beautiful/ }).click();
  await expect(page).toHaveURL(/\/w\/en\/beautiful$/);
});

test("autocomplete suggests words", async ({ page }) => {
  await page.goto("/");
  await searchBox(page).fill("be");
  await expect(page.getByRole("option", { name: /beautiful/ })).toBeVisible();
});

test("reverse lookup and natural-language query", async ({ page }) => {
  await search(page, "yugurmoq");
  await expect(page.getByTestId("search-results")).toContainText("run");
  await search(page, "2026-yilda AI sohasida chiqqan yangi terminlarni ko‘rsat");
  await expect(page.getByTestId("search-results")).toContainText("vibe coding");
});

test("unknown word is generated by AI and explained", async ({ page }) => {
  const term = randomWord("zorbex");
  await page.goto(`/search?q=${term}&from=en`);
  await expect(page).toHaveURL(new RegExp(`/w/en/${term}$`), { timeout: 30_000 });
  await expect(page.getByTestId("ai-badge")).toContainText("AI tomonidan yaratilgan");

  await page.goto("/w/en/run");
  await page.getByTestId("ai-panel").getByRole("button", { name: "Sodda" }).click();
  await expect(page.getByTestId("ai-panel")).toContainText("sodda izoh");
});

test("translator uses the dictionary for single words", async ({ page }) => {
  await page.goto("/translate");
  await page.getByLabel("Matn kiriting…").fill("run");
  await page.getByRole("button", { name: "Tarjima qilish" }).click();
  await expect(page.getByTestId("translation-result")).toContainText("yugurmoq");
  await expect(page.getByTestId("translation-result")).toContainText("Lug‘atdan");
});

test("interface language can be switched", async ({ page }) => {
  await page.goto("/");
  await page.getByLabel("Interfeys tili").selectOption("en");
  await expect(page.getByRole("link", { name: "Translate" })).toBeVisible();
  await page.getByLabel("Interface language").selectOption("uz");
  await expect(page.getByRole("link", { name: "Tarjima" })).toBeVisible();
});
